# Generated by Django 2.2.4 on 2022-09-27 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0007_auto_20220926_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='dojo_id_key',
            new_name='dojo',
        ),
    ]
