# Generated by Django 2.2.4 on 2022-09-27 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0008_auto_20220927_0612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='dojo',
            new_name='dojo_id',
        ),
    ]
