# Generated by Django 2.2.4 on 2022-09-27 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0009_auto_20220927_0617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='dojo_id',
            new_name='dojo',
        ),
    ]
