# Generated by Django 2.2.4 on 2022-09-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dojo',
            name='state',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
