# Generated by Django 2.2.4 on 2022-09-29 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0002_auto_20220929_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateField(default=datetime.date(2022, 9, 29)),
        ),
    ]
