# Generated by Django 2.2.4 on 2022-09-29 14:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0003_auto_20220929_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 29, 14, 18, 11, 227817, tzinfo=utc)),
        ),
    ]
